// Rebuild: dart run tool/build_dictionary.dart <WordNet-3.0.tar.gz>
import 'dart:convert';
import 'dart:io';

import 'package:archive/archive.dart';
import 'package:crypto/crypto.dart';

void main(List<String> args) {
  if (args.length != 1) {
    throw ArgumentError('Provide the WordNet 3.0 tar.gz archive');
  }
  final source = File(args.single).readAsBytesSync();
  final archive = TarDecoder().decodeBytes(gzip.decode(source));
  String read(String suffix) => utf8.decode(
    archive.files.singleWhere((f) => f.name.endsWith('/$suffix')).content,
  );
  final entries = <String, List<List<String>>>{};
  final valid = RegExp(r"^[a-z]+(?:['-][a-z]+)*$");
  for (final (pos, label) in [
    ('noun', 'noun'),
    ('verb', 'verb'),
    ('adj', 'adjective'),
    ('adv', 'adverb'),
  ]) {
    final glosses = <String, String>{};
    for (final line in const LineSplitter().convert(read('dict/data.$pos'))) {
      if (line.startsWith(' ') || !line.contains('|')) continue;
      glosses[line.substring(0, 8)] = line
          .substring(line.indexOf('|') + 1)
          .trim();
    }
    final byPos = <String, List<List<String>>>{};
    for (final line in const LineSplitter().convert(read('dict/index.$pos'))) {
      if (line.startsWith(' ') || line.isEmpty) continue;
      final fields = line.trim().split(RegExp(r'\s+'));
      final word = fields.first;
      if (!valid.hasMatch(word)) continue;
      final offsets = fields.skip(6 + int.parse(fields[3]));
      final senses = offsets
          .map((offset) => [label, glosses[offset]!])
          .toList();
      byPos[word] = senses;
      entries.putIfAbsent(word, () => []).addAll(senses);
    }
    for (final line in const LineSplitter().convert(read('dict/$pos.exc'))) {
      final fields = line.trim().split(RegExp(r'\s+'));
      if (!valid.hasMatch(fields.first)) continue;
      for (final base in fields.skip(1)) {
        final senses = byPos[base];
        if (senses == null) continue;
        final target = entries.putIfAbsent(fields.first, () => []);
        for (final sense in senses) {
          if (!target.any((s) => s[0] == sense[0] && s[1] == sense[1])) {
            target.add(sense);
          }
        }
      }
    }
  }
  final shards = <String, Map<String, List<List<String>>>>{};
  const letters = 'abcdefghijklmnopqrstuvwxyz';
  for (final first in letters.split('')) {
    for (final second in '${letters}_'.split('')) {
      shards['$first$second'] = {};
    }
  }
  for (final word in entries.keys.toList()..sort()) {
    final second = word.length > 1 && letters.contains(word[1]) ? word[1] : '_';
    shards['${word[0]}$second']![word] = entries[word]!;
  }
  final directory = Directory('assets/dictionary')..createSync(recursive: true);
  var bytes = 0;
  for (final shard in shards.entries) {
    final data = gzip.encode(utf8.encode(jsonEncode(shard.value)));
    File('${directory.path}/${shard.key}.json.gz').writeAsBytesSync(data);
    bytes += data.length;
  }
  File('${directory.path}/LICENSE.txt').writeAsStringSync(read('LICENSE'));
  File('${directory.path}/SOURCE.txt').writeAsStringSync(
    'Offline English dictionary derived from WordNet 3.0.\n'
    'Source: https://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz\n'
    'Archive SHA-256: ${sha256.convert(source)}\n'
    'Generated by tool/build_dictionary.dart.\n'
    'Includes single-word lemmas, senses in source order, and irregular forms.\n'
    'Entries: ${entries.length}; compressed bytes: $bytes; shards: ${shards.length}.\n'
    'The WordNet license is included in LICENSE.txt.\n',
  );
  stdout.writeln('${entries.length} entries, $bytes compressed bytes');
}
